--------------------------------------------------------
--  File created - Friday-April-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EPAY_COUNTRY
--------------------------------------------------------

  CREATE TABLE "EPAY_COUNTRY" 
   (	"COU_CODE" VARCHAR2(2), 
	"COU_DISPLAYNAME" VARCHAR2(150), 
	"COU_CODE3" VARCHAR2(3), 
	"COU_STATUS" NUMBER, 
	"COU_STATUSDESC" VARCHAR2(150), 
	"COU_CREATEDON" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"COU_MODIFIEDON" TIMESTAMP (6), 
	"COU_CREATEDBY" VARCHAR2(16), 
	"COU_MODIFIEDBY" VARCHAR2(16)
   )
--------------------------------------------------------
--  DDL for Table EPAY_CURRENCY
--------------------------------------------------------

  CREATE TABLE "EPAY_CURRENCY" 
   (	"CUR_CODE" VARCHAR2(3), 
	"CUR_DISPLAYNAME" NVARCHAR2(150), 
	"CUR_DISPLAYSYMBOL" VARCHAR2(20), 
	"CUR_DECIMALPLACE" NUMBER, 
	"CUR_STATUS" NUMBER, 
	"CUR_STATUSDESC" NVARCHAR2(150), 
	"COU_CODE" VARCHAR2(2), 
	"CUR_CREATEDON" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CUR_MODIFIEDON" TIMESTAMP (6), 
	"CUR_CREATEDBY" VARCHAR2(16), 
	"CUR_MODIFIEDBY" VARCHAR2(16)
   )
--------------------------------------------------------
--  DDL for Table EPAY_MESSAGE_INLOG
--------------------------------------------------------

  CREATE TABLE "EPAY_MESSAGE_INLOG" 
   (	"MSG_UUID" VARCHAR2(36), 
	"MSG_CREATEDON" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"MSG_SOURCECHANNEL" VARCHAR2(5), 
	"MSG_TYPE" VARCHAR2(6), 
	"MSG_SUBTYPE" VARCHAR2(6), 
	"MSG_MESSAGE" BLOB, 
	"MSG_STATUS" NUMBER, 
	"MSG_STATUSDESC" NVARCHAR2(150), 
	"MSG_LOCATION" VARCHAR2(255), 
	"MSG_MODIFIEDON" TIMESTAMP (6), 
	"MSG_CREATEDBY" VARCHAR2(16), 
	"MSG_MODIFIEDBY" VARCHAR2(16), 
	"MSG_RESPONSE" BLOB, 
	"MSG_REQUESTPATH" VARCHAR2(255), 
	"MSG_RESPONSEPATH" VARCHAR2(255), 
	"MSG_VERSION" NUMBER DEFAULT 0
   )
--------------------------------------------------------
--  DDL for Table EPAY_PAYMENT_INDETAILS
--------------------------------------------------------

  CREATE TABLE "EPAY_PAYMENT_INDETAILS" 
   (	"PAYIND_UUID" VARCHAR2(36), 
	"PAYIN_UUID" VARCHAR2(36), 
	"PAYIND_TRANSACTIONREFERENCE" VARCHAR2(36), 
	"PAYIND_SENDERREFERENCE" VARCHAR2(36), 
	"PAYIND_CUSTSPECREF_RETURN" VARCHAR2(16), 
	"PAYIND_MSGINDEX" VARCHAR2(11), 
	"PAYIND_STATUS" NUMBER, 
	"PAYIND_STATUSDESC" VARCHAR2(150), 
	"PAYIND_ORIGINALVALUEDATE" DATE, 
	"PAYIND_APPLICABLEVALUEDATE" DATE, 
	"PAYIND_TRADEDATE" DATE, 
	"CUR_CODE" VARCHAR2(3), 
	"PAYIND_DBTCURRENCY" VARCHAR2(3), 
	"PAYIND_CRDCURRENCY" VARCHAR2(20), 
	"PAYIND_INSTRUCTINGPARTY" VARCHAR2(36), 
	"PAYIND_TAG50FGH_ORDERINGCUST" VARCHAR2(35), 
	"PAYIND_TAG50_ORDERINGDETAIL1" VARCHAR2(35), 
	"PAYIND_TAG50_ORDERINGDETAIL2" VARCHAR2(35), 
	"PAYIND_TAG50_ORDERINGDETAIL3" VARCHAR2(35), 
	"PAYIND_TAG50_ORDERINGDETAIL4" VARCHAR2(35), 
	"PAYIND_ORDERINGREGISTERED" VARCHAR2(150), 
	"PAYIND_TRANSACTIONAMOUNT" NUMBER, 
	"PAYIND_DEBITAMOUNT" NUMBER, 
	"PAYIND_CREDITAMOUNT" NUMBER, 
	"PAYIND_FXDEALREF" VARCHAR2(16), 
	"PAYIND_TAG23_INSTRCODE" VARCHAR2(35), 
	"PAYIND_TAG52_ACCSRVINST" VARCHAR2(35), 
	"PAYIND_TAG57_ACCWTHINST" VARCHAR2(35), 
	"PAYIND_TAG57_ACCWTHINST1" VARCHAR2(35), 
	"PAYIND_TAG57_ACCWTHINST2" VARCHAR2(35), 
	"PAYIND_TAG57_ACCWTHINST3" VARCHAR2(35), 
	"PAYIND_TAG57_ACCWTHINST4" VARCHAR2(35), 
	"PAYIND_TAG59_BENEFICARY" VARCHAR2(35), 
	"PAYIND_TAG59_DETAILS1" VARCHAR2(35), 
	"PAYIND_TAG59_DETAILS2" VARCHAR2(35), 
	"PAYIND_TAG59_DETAILS3" VARCHAR2(35), 
	"PAYIND_TAG59_DETAILS4" VARCHAR2(35), 
	"PAYIND_TAG70_DETAILS1" VARCHAR2(35), 
	"PAYIND_TAG70_DETAILS2" VARCHAR2(35), 
	"PAYIND_TAG70_DETAILS3" VARCHAR2(35), 
	"PAYIND_TAG70_DETAILS4" VARCHAR2(35), 
	"PAYIND_TAG77_DETAILS1" VARCHAR2(35), 
	"PAYIND_TAG77_DETAILS2" VARCHAR2(35), 
	"PAYIND_TAG77_DETAILS3" VARCHAR2(35), 
	"PAYIND_TAG71_DETAILSOFCHARGE" VARCHAR2(3), 
	"PAYIND_CHARGEACC" VARCHAR2(35), 
	"PAYIND_EXCH_RATE" NUMBER, 
	"PAYIND_EXCH_BUYSELL" VARCHAR2(1), 
	"PAYIND_COMMISSION" NUMBER, 
	"PAYIND_CHARGEAMOUNT" NUMBER, 
	"PAYIND_CREATEDON" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"PAYIND_MODIFIEDON" TIMESTAMP (6), 
	"PAYIND_CREATEDBY" VARCHAR2(16), 
	"PAYIND_MODIFIEDBY" VARCHAR2(16), 
	"PAYIND_APPROVEDBY" VARCHAR2(16), 
	"PAYIND_AUTHORIZEDBY" VARCHAR2(16), 
	"PAYIND_APPROVEDON" TIMESTAMP (6), 
	"PAYIND_MT199REPLY_STATUS" NUMBER, 
	"PAYIND_MT199REPLY" BLOB, 
	"PAYIND_MT199GENERATED" TIMESTAMP (6), 
	"PAYIND_VALIDATEDON" TIMESTAMP (6), 
	"PAYIND_POSTEDON" TIMESTAMP (6)
   )
--------------------------------------------------------
--  DDL for Table EPAY_PAYMENT_INHEADER
--------------------------------------------------------

  CREATE TABLE "EPAY_PAYMENT_INHEADER" 
   (	"PAYIN_UUID" VARCHAR2(36), 
	"PAYIN_MESSAGEREFERNCE" VARCHAR2(36), 
	"CUSTOMER_UUID" VARCHAR2(36), 
	"PAYIN_TYPE" VARCHAR2(6), 
	"PAYIN_SOURCECHANNEL" VARCHAR2(5), 
	"PAYIN_STATUS" NUMBER, 
	"PAYIN_STATUSDESC" NVARCHAR2(150), 
	"PAYIN_SERVICETYPE" VARCHAR2(20), 
	"PAYIN_CUSTBNKOTHMSG" NUMBER, 
	"PAYIN_RECEIVEDCOUNT" NUMBER DEFAULT 0, 
	"PAYIN_PROCESSEDCOUNT" NUMBER DEFAULT 0, 
	"PAYIN_REJECTEDCOUNT" NUMBER DEFAULT 0, 
	"PAYIN_ERRORCOUNT" NUMBER DEFAULT 0, 
	"PAYIN_OWN_TRANSFERCOUNT" NUMBER DEFAULT 0, 
	"PAYIN_ATA_TRANSFERCOUNT" NUMBER DEFAULT 0, 
	"PAYIN_LOC_TRANSFERCOUNT" NUMBER DEFAULT 0, 
	"PAYIN_INT_TRANSFERCOUNT" NUMBER DEFAULT 0, 
	"PAYIN_RECEIVEDAMOUNT" NUMBER, 
	"PAYIN_PROCESSEDAMOUNT" NUMBER, 
	"PAYIN_FAILEDAMOUNT" NUMBER, 
	"MSG_UUID" VARCHAR2(36), 
	"PAYIN_UTERUUID" VARCHAR2(40), 
	"PAYIN_CREATEDON" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"PAYIN_MODIFIEDON" TIMESTAMP (6), 
	"PAYIN_CREATEDBY" VARCHAR2(16), 
	"PAYIN_MODIFIEDBY" VARCHAR2(16), 
	"PAYIN_VERSION" NUMBER DEFAULT 0
   )
REM INSERTING into EPAY_COUNTRY
SET DEFINE OFF;
REM INSERTING into EPAY_CURRENCY
SET DEFINE OFF;
REM INSERTING into EPAY_MESSAGE_INLOG
SET DEFINE OFF;
REM INSERTING into EPAY_PAYMENT_INDETAILS
SET DEFINE OFF;
REM INSERTING into EPAY_PAYMENT_INHEADER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index IDX_PAYHEAD_CREATED
--------------------------------------------------------

  CREATE INDEX "IDX_PAYHEAD_CREATED" ON "EPAY_PAYMENT_INHEADER" ("PAYIN_CREATEDON" DESC)
--------------------------------------------------------
--  DDL for Index IDX_PAYHEAD_STATUS
--------------------------------------------------------

  CREATE INDEX "IDX_PAYHEAD_STATUS" ON "EPAY_PAYMENT_INHEADER" ("PAYIN_STATUS")
--------------------------------------------------------
--  DDL for Index IDX_MSG_INCREATEDON
--------------------------------------------------------

  CREATE INDEX "IDX_MSG_INCREATEDON" ON "EPAY_MESSAGE_INLOG" ("MSG_CREATEDON" DESC)
--------------------------------------------------------
--  DDL for Index PK_PAYIN_HEADERID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PAYIN_HEADERID" ON "EPAY_PAYMENT_INHEADER" ("PAYIN_UUID")
--------------------------------------------------------
--  DDL for Index PK_CURRENCY_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CURRENCY_CODE" ON "EPAY_CURRENCY" ("CUR_CODE")
--------------------------------------------------------
--  DDL for Index IDX_CURRENCY_STATUS
--------------------------------------------------------

  CREATE INDEX "IDX_CURRENCY_STATUS" ON "EPAY_CURRENCY" ("CUR_STATUS" DESC)
--------------------------------------------------------
--  DDL for Index IDX_INDETAIL_CREATED
--------------------------------------------------------

  CREATE INDEX "IDX_INDETAIL_CREATED" ON "EPAY_PAYMENT_INDETAILS" ("PAYIN_UUID")
--------------------------------------------------------
--  DDL for Index PK_MSG_INLOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MSG_INLOG" ON "EPAY_MESSAGE_INLOG" ("MSG_UUID")
--------------------------------------------------------
--  DDL for Index IDX_COUNTRY_STATUS
--------------------------------------------------------

  CREATE INDEX "IDX_COUNTRY_STATUS" ON "EPAY_COUNTRY" ("COU_STATUS")
--------------------------------------------------------
--  DDL for Index PK_INDETAIL_UUID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_INDETAIL_UUID" ON "EPAY_PAYMENT_INDETAILS" ("PAYIND_UUID")
--------------------------------------------------------
--  DDL for Index IDX_CURRENCY_CREATEDON
--------------------------------------------------------

  CREATE INDEX "IDX_CURRENCY_CREATEDON" ON "EPAY_CURRENCY" ("CUR_CREATEDON" DESC)
--------------------------------------------------------
--  DDL for Index PK_COUNTRY_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_COUNTRY_CODE" ON "EPAY_COUNTRY" ("COU_CODE")
--------------------------------------------------------
--  DDL for Index IDX_MSG_INTYPE
--------------------------------------------------------

  CREATE INDEX "IDX_MSG_INTYPE" ON "EPAY_MESSAGE_INLOG" ("MSG_TYPE")
--------------------------------------------------------
--  Constraints for Table EPAY_MESSAGE_INLOG
--------------------------------------------------------

  ALTER TABLE "EPAY_MESSAGE_INLOG" MODIFY ("MSG_MESSAGE" NOT NULL ENABLE)
  ALTER TABLE "EPAY_MESSAGE_INLOG" MODIFY ("MSG_VERSION" NOT NULL ENABLE)
  ALTER TABLE "EPAY_MESSAGE_INLOG" ADD CONSTRAINT "PK_MSG_INLOG" PRIMARY KEY ("MSG_UUID") ENABLE
  ALTER TABLE "EPAY_MESSAGE_INLOG" MODIFY ("MSG_CREATEDBY" NOT NULL ENABLE)
  ALTER TABLE "EPAY_MESSAGE_INLOG" MODIFY ("MSG_STATUS" NOT NULL ENABLE)
  ALTER TABLE "EPAY_MESSAGE_INLOG" MODIFY ("MSG_TYPE" NOT NULL ENABLE)
  ALTER TABLE "EPAY_MESSAGE_INLOG" MODIFY ("MSG_CREATEDON" NOT NULL ENABLE)
  ALTER TABLE "EPAY_MESSAGE_INLOG" MODIFY ("MSG_UUID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EPAY_COUNTRY
--------------------------------------------------------

  ALTER TABLE "EPAY_COUNTRY" ADD CONSTRAINT "PK_COUNTRY_CODE" PRIMARY KEY ("COU_CODE") ENABLE
  ALTER TABLE "EPAY_COUNTRY" MODIFY ("COU_CREATEDON" NOT NULL ENABLE)
  ALTER TABLE "EPAY_COUNTRY" MODIFY ("COU_DISPLAYNAME" NOT NULL ENABLE)
  ALTER TABLE "EPAY_COUNTRY" MODIFY ("COU_CODE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EPAY_CURRENCY
--------------------------------------------------------

  ALTER TABLE "EPAY_CURRENCY" ADD CONSTRAINT "PK_CURRENCY_CODE" PRIMARY KEY ("CUR_CODE") ENABLE
  ALTER TABLE "EPAY_CURRENCY" MODIFY ("CUR_CREATEDON" NOT NULL ENABLE)
  ALTER TABLE "EPAY_CURRENCY" MODIFY ("CUR_STATUS" NOT NULL ENABLE)
  ALTER TABLE "EPAY_CURRENCY" MODIFY ("CUR_CODE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EPAY_PAYMENT_INDETAILS
--------------------------------------------------------

  ALTER TABLE "EPAY_PAYMENT_INDETAILS" ADD CONSTRAINT "PK_INDETAIL_UUID" PRIMARY KEY ("PAYIND_UUID") ENABLE
  ALTER TABLE "EPAY_PAYMENT_INDETAILS" MODIFY ("PAYIND_TRANSACTIONREFERENCE" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INDETAILS" MODIFY ("PAYIN_UUID" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INDETAILS" MODIFY ("PAYIND_UUID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EPAY_PAYMENT_INHEADER
--------------------------------------------------------

  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_VERSION" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" ADD CONSTRAINT "PK_PAYIN_HEADERID" PRIMARY KEY ("PAYIN_UUID") ENABLE
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_CREATEDON" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_INT_TRANSFERCOUNT" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_LOC_TRANSFERCOUNT" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_ATA_TRANSFERCOUNT" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_OWN_TRANSFERCOUNT" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_ERRORCOUNT" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_REJECTEDCOUNT" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_PROCESSEDCOUNT" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_RECEIVEDCOUNT" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_SOURCECHANNEL" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_MESSAGEREFERNCE" NOT NULL ENABLE)
  ALTER TABLE "EPAY_PAYMENT_INHEADER" MODIFY ("PAYIN_UUID" NOT NULL ENABLE)
